-- -------------------------------------------------------------
-- 
-- File Name: /home/dominik/Dokumenty/przedmioty/IMAS/imas-project/codegen/sha256/hdlsrc/sha256.vhd
-- Created: 2017-05-16 19:59:38
-- 
-- Generated by MATLAB 9.2, MATLAB Coder 3.3 and HDL Coder 3.10
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: sha256
-- Source Path: sha256
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;

package sha256_types is

	type expanded_message_block_array is array(0 to 63) of std_logic_vector(31 downto 0);

	type constant_array is array(0 to 63) of std_logic_vector(31 downto 0);

end package;
